boofuzz’s web-GUI logging listen to any address
jtpereyda/boofuzz pull request #611
Opened 2022-03-16 21:09 UTC by tin-z

Choose which address expose boofuzz’s web-GUI logging, with 'localhost' as the default value.

2022-03-21 13:27 UTC, jtpereyda requested changes

2022-03-21 23:38 UTC, tin-z commented on boofuzz/fuzz_logger_curses.py
> +        self._address_listening = address_listening
Ok ;)

2022-03-22 14:08 UTC, jtpereyda approved these changes
Looks good! Would you mind adding a line to CHANGELOG.rst under upcoming features?

2022-03-22 14:10 UTC, jtpereyda commented
Oh, and see also the stickler-ci finding on line 343.

2022-03-22 22:19 UTC, tin-z commented
Ok done!

Now i see a timeout  as result in executing 'Python 3.7 on windows-latest' test

2022-03-22 22:32 UTC, SR4ven commented
The run was just suck. It happens from time to time, rerunning it worked.
Thanks for your work @tin-z

2022-03-22 22:34 UTC, merged

2022-03-22 22:46 UTC, tin-z commented
Thank you! Have a nice one